version: '2'
services:
    minio:
        image: minio/minio:latest
        container_name: minio
        environment:
            MINIO_ROOT_USER: localid
            MINIO_ROOT_PASSWORD: localpassword
        entrypoint: bash
        command: -c "/opt/bin/minio server /export --address :9999 --console-address :9001"
        volumes:
            - ./minio_data:/export
        ports:
            - '9000:9999'
            - '9001:9001'
